org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=HyInfo
mod_id=hyinfo
mod_version=3.0.0
mod_description=Minecraft mod for Hypixel adding levelhead, BedWars stars, SkyWars stars and Duels division display in Tablist and above nametags
mod_archives_name=HyInfo
base_group=tomeko.hyinfo

java_version=[VERSIONED]
minecraft_version=[VERSIONED]

fabric_loader_version=0.19.5
fabric_api_version=[VERSIONED]
osl_version=0.21.0

oneconfig_version=[VERSIONED]
hypixel_mod_api_version=[VERSIONED]
mod_menu_version=[VERSIONED]

stonecutter_version=0.10-alpha.8