org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=HyMod
mod_id=hymod
mod_version=2.2.1
mod_description=Multiversion mod for Hypixel and Ranked BedWars adding features for BedWars (resource display), stats, levelhead, chat waypoints and more!
mod_archives_name=HyMod
base_group=tomeko.hymod

java_version=[VERSIONED]
minecraft_version=[VERSIONED]

fabric_loader_version=0.19.5
fabric_api_version=[VERSIONED]
osl_version=0.21.0

oneconfig_version=[VERSIONED]
hypixel_mod_api_version=[VERSIONED]
mod_menu_version=[VERSIONED]

stonecutter_version=0.10-alpha.8